(()=>{
'use strict';const httpMode=location.protocol==='http:';let token=document.querySelector('meta[name="yjb-token"]')?.content;
const style=document.createElement('style');style.textContent='.backend-controls{background:#fff;border:1px solid #dae5ec;border-radius:10px;padding:16px 20px;margin:0 0 20px;font:14px/1.6 "Microsoft YaHei",sans-serif;color:#183248}.backend-controls .controls{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.backend-controls button,.backend-controls select{padding:7px 12px;border:1px solid #c9d8e2;border-radius:7px;background:white;color:#183248;font:inherit;cursor:pointer}.backend-controls button.primary{background:#087e8b;color:white}.backend-controls button:disabled{opacity:.55;cursor:wait}.backend-controls p{margin:8px 0 0;font-size:12px;color:#677f90}.backend-controls details{margin-top:8px}.backend-controls a{color:#087e8b}.backend-controls .error{color:#a76313}';document.head.append(style);
const box=document.createElement('section');box.className='backend-controls';box.innerHTML='<div class="controls"><button id="backend-refresh" class="primary">后台刷新数据</button><label>自动刷新 <select id="backend-interval"><option value="0">关闭</option><option value="10">每10分钟</option><option value="30" selected>每30分钟</option><option value="60">每小时</option><option value="120">每2小时</option></select></label><button id="backend-save">保存间隔</button><button id="backend-view" hidden>查看更新后的看板</button></div><p id="backend-status" role="status">正在连接本地后台…</p><details><summary>后台与Edge资料设置</summary><p>自动刷新仅在北京时间交易日09:30–11:30、13:00–15:00运行，午休、收盘后与休市日暂停。手动按钮随时可用。关闭浏览器后后台仍运行，关机后停止。</p><div class="controls" style="margin-top:8px"><label>Edge资料 <select id="backend-profile"><option value="">自动检测</option></select></label><button id="backend-profile-save">保存资料</button><button id="backend-stop">停止后台</button></div><p>已有截图仍需先同步到养基宝APP与Edge插件，定时读取不会替你更新支付宝截图。</p></details>';
const target=document.querySelector('main')||document.body;target.insertBefore(box,target.firstChild);
const $=id=>document.getElementById(id),status=$('backend-status');let stopped=false,inflight=false,seenVersion=null,seenFinished=null,configured=false,wasBusy=false;
if(!httpMode){status.innerHTML='后台刷新需要先双击项目里的“启动看板.vbs”。启动后请使用自动打开的浏览器页面。<a href="http://127.0.0.1:8787/">打开本地后台</a>';['backend-refresh','backend-save','backend-profile-save','backend-stop'].forEach(id=>$(id).disabled=true);return;}
async function post(route,data={}){const r=await fetch(route,{method:'POST',headers:{'Content-Type':'application/json','X-YJB-Token':token},body:JSON.stringify(data)});const result=await r.json();if(!r.ok)throw new Error(result.error||'操作失败');return result;}
function remember(){const tab=document.querySelector('[data-tab].active')?.dataset.tab;if(tab)sessionStorage.setItem('yjb.activeTab',tab);sessionStorage.setItem('yjb.scroll',String(scrollY));}
function reload(){remember();location.reload();}
const savedTab=sessionStorage.getItem('yjb.activeTab');if(savedTab)document.querySelector('[data-tab="'+savedTab+'"]')?.click();const scroll=Number(sessionStorage.getItem('yjb.scroll')||0);if(scroll)setTimeout(()=>window.scrollTo(0,scroll),50);
const formatted=d=>d?new Date(d).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'—';
function busyEditing(){const tag=document.activeElement?.tagName;return ['INPUT','TEXTAREA','SELECT'].includes(tag)||!!$('jreason')?.value?.trim();}
async function poll(){if(stopped||inflight)return;inflight=true;try{const r=await fetch('/api/status',{cache:'no-store'});if(!r.ok)throw new Error('后台状态不可用');const s=await r.json();if(!configured){$('backend-interval').value=String(s.config.refreshMinutes);const profiles=$('backend-profile');for(const p of s.profiles){const o=document.createElement('option');o.value=p.path;o.textContent=p.name;profiles.append(o);}profiles.value=s.config.edgeProfile;configured=true;}
const baseline=seenVersion===null;const changed=!baseline&&s.version!==seenVersion;seenVersion=s.version;
$('backend-refresh').disabled=s.busy;$('backend-refresh').textContent=s.busy?'后台刷新中…':'后台刷新数据';status.classList.toggle('error',!s.busy&&s.lastResult?.ok===false);status.textContent=s.busy?s.phase:((s.lastResult?.message||'后台已就绪')+(s.lastFinished?'；完成于 '+formatted(s.lastFinished):'')+'；'+(s.scheduleStatus||'后台已就绪')+(s.nextAt?'；下次 '+formatted(s.nextAt):''));
if(changed){if(busyEditing()){$('backend-view').hidden=false;status.textContent+='；有新数据，填写完成后点击“查看更新后的看板”';}else{reload();return;}}seenFinished=s.lastFinished;wasBusy=s.busy;
}catch(e){status.classList.add('error');status.textContent='本地后台未运行或已停止，请双击“启动看板.vbs”重新启动。';}finally{inflight=false;}}
$('backend-refresh').onclick=async()=>{try{$('backend-refresh').disabled=true;await post('/api/refresh');await poll();}catch(e){status.textContent=e.message;$('backend-refresh').disabled=false;}};
$('backend-save').onclick=async()=>{try{await post('/api/config',{refreshMinutes:Number($('backend-interval').value)});await poll();}catch(e){status.textContent=e.message;}};
$('backend-profile-save').onclick=async()=>{try{await post('/api/config',{edgeProfile:$('backend-profile').value});status.textContent='Edge资料已保存；点击后台刷新读取持仓。';}catch(e){status.textContent=e.message;}};
$('backend-view').onclick=reload;$('backend-stop').onclick=async()=>{try{await post('/api/stop');stopped=true;status.textContent='后台已停止，自动刷新已关闭。双击启动看板可重新启动。';$('backend-refresh').disabled=true;$('backend-stop').disabled=true;}catch(e){status.textContent=e.message;}};
poll();setInterval(poll,2500);
})();
